### ISSUE TITLE
Using pasha for experiments 

### ISSUE THREAD

**Issue by anuradhawick** [ekimb/pasha#1]
Hello,

Really appreciate this implementation and I can see that it works faster than the original java implementation. I am planning to use UHS in some of my research work and wonder if I could use the binaries compiled from this repo. What does `runpasha.sh` do? Does it generate all UHS kmers for all the k values and L values?

Thanks.

**Comment by ekimb** [comment]
Hey there!

`runpasha.sh` was an artifact of some recent tests - sorry about that!

The repo does not have precompiled binaries, but you can compile binaries by cloning the repo and compiling with g++:

`g++ -O3 -o pasha rand.cpp -fopenmp`

and execute with:

`./pasha $K $L $THREADS $DECYCPATH $ADDPATH`

Feel free to let me know if you have any other questions or close the issue if this helps!

**Comment by anuradhawick** [comment]
Thanks. I found that you have pre-computed UHS for several K values and L values. Very useful.
